### ISSUE TITLE
How to setup the folder structure?

### ISSUE THREAD

**Issue by ankurguria** [lannguyen0910/deep-efficient-person-reid#1]
1) Could you please share in which folder the datasets and pre-trained weights should be downloaded and placed?

2) Thanks for sharing the colab notebook (makes it very easy to test the code). Could you add the code to automatically download (wget) the datasets and pre-trained weights in the right folder in the notebook itself? Else it is quite confusing how to set up the directories to run the code.

Thank you for sharing the code with the community. @lannguyen0910

**Comment by ankurguria** [comment]
@lannguyen0910

**Comment by jhq1234** [comment]
When I run a code 'python train.py --config_file=resnet50_cuhk', the train starts successfully but at the end, after 50 epoch, an error occurs like this 'ValueError: too many values to unpack (expected 3)'
How can I solve this problem?

**Comment by vinesin** [comment]
@ankurguria Where you able to download the pre-trained weights and set up the directories? If yes, please share how you did so.

**Comment by lannguyen0910** [comment]
Hi @ankurguria, i'm sorry for my late reply. I have updated the notebook according to your suggestions. If you have any other issues, please reach out to me soon. Thank you and have a nice day!
