### ISSUE TITLE
Download links for Pretrained weights not working

### ISSUE THREAD

**Issue by chandantarani** [lannguyen0910/deep-efficient-person-reid#9]
First of all, thank you for the amazing work!

It seems that the links to download the ImageNet pre-trained models, datasets, and EfficientNet-v2 and Resnet50-IBN-A  are not working, giving a 404 page not found error.

**Comment by chandantarani** [comment]
![Uploading 404.png…]()

**Comment by chandantarani** [comment]
![404](https://user-images.githubusercontent.com/31465082/133892108-86dae602-6b54-4c38-a62d-e662cb191e77.png)

**Comment by xuarehere** [comment]
Thank you for the amazing work!
and i meet the same problem, have somebody solve the problem?
